# -*- coding: utf-8 -*-
"""kalkulator tabung v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WrYy_WAxYa3wOtJhd1hY9lCV-PER23Ks
"""

import streamlit as st
import math

def hitung_volume_tabung(jari_jari, tinggi):
  """
  Menghitung volume tabung berdasarkan jari-jari dan tingginya.

  Args:
    jari_jari: Jari-jari alas tabung.
    tinggi: Tinggi tabung.

  Returns:
    Volume tabung.
  """
  volume = math.pi * (jari_jari ** 2) * tinggi
  return volume

st.title("Kalkulator Volume Tabung")
st.write("Aplikasi sederhana untuk menghitung volume tabung.")

# Input dari pengguna
st.header("Masukkan Dimensi Tabung")

jari_jari_input = st.number_input("Masukkan jari-jari tabung (cm):", min_value=0.0, value=5.0)
tinggi_input = st.number_input("Masukkan tinggi tabung (cm):", min_value=0.0, value=10.0)

# Tombol untuk menghitung
if st.button("Hitung Volume"):
  if jari_jari_input <= 0 or tinggi_input <= 0:
    st.error("Jari-jari dan tinggi harus lebih besar dari nol.")
  else:
    volume_hasil = hitung_volume_tabung(jari_jari_input, tinggi_input)
    st.success(f"Volume tabung adalah: **{volume_hasil:.2f} cm³**")
    st.balloons() # Efek balon setelah perhitungan